stages:
  load:
    cmd: hibayes-load --config files/config.yaml --out .output/load/
    deps:
    - ../../src/hibayes/
    - files/extractors.py
    outs:
    - .output/load/
    params:
      - files/config.yaml:
        - data_loader
  model:
    cmd: hibayes-model --config files/config.yaml --data .output/load/data.parquet
      --out .output/model/
    deps:
    - ../../src/hibayes/
    - .output/load/data.parquet
    - files/custom_checker.py
    outs:
    - .output/model/
    params:
      - files/config.yaml:
        - model
        - checkers
        - platform
  communicate:
    cmd: hibayes-comm --config files/config.yaml --analysis_state .output/model/ --out .output/communicate/
    deps:
    - ../../src/hibayes/
    - .output/model/
    outs:
    - .output/communicate/
    params:
      - files/config.yaml:
        - communicate
